---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_zero

platforms:
  - name: amazon-v2
    driver_config:
      image: phenompeople/amazonlinux-ccb:V2
      platform: centos
      privileged: true
      volume: /sys/fs/cgroup
      remove_images: false

  - name: amazon-2018.03
    driver_config:
      image: phenompeople/amazonlinux-ccb:2018.03
      platform: centos
      privileged: true
      volume: /sys/fs/cgroup
      remove_images: false


  - name: centos-7.3
    driver_config:
      image: phenompeople/centos-ccb:7.3.1611
      platform: centos
      run_command: /usr/sbin/init
      privileged: true
      volume:
        - /sys/fs/cgroup:/sys/fs/cgroup
      remove_images: true

  - name: centos-7.2
    driver_config:
      image: phenompeople/centos-ccb:7.2.1511
      platform: centos
      run_command: /usr/sbin/init
      privileged: true
      volume:
        - /sys/fs/cgroup:/sys/fs/cgroup
      remove_images: true

  - name: ubuntu-14.04
    driver_config:
      image: phenompeople/ubuntu-ccb:14.04
      platform: ubuntu
      remove_images: true

  - name: ubuntu-16.04
    driver_config:
      image: phenompeople/ubuntu-ccb:16.04
      platform: ubuntu
      remove_images: true

suites:
  - name: deploy_user
    run_list:
      - recipe[basic-essentials::oracle_java_default]
      - recipe[build-essentials::deploy_user_assemble]
      - recipe[basic-essentials::gitclient]
      - recipe[build-essentials::buildproperties_repo]
      - recipe[build-essentials::maven_install]
#      - recipe[build-essentials::deploy_user_dismantle]
    attributes:

  - name: maven
    run_list:
      - recipe[basic-essentials::oracle_java_default]
      - recipe[build-essentials::maven_install]
    attributes:

  - name: nodejs
    run_list:
      - recipe[build-essentials::nodejs_install]
#      - recipe[build-essentials::nodejs_uninstall]
  - name: python3
    run_list:
      - recipe[build-essentials::python3]
    attributes:
