---
driver:
 name: vagrant

provisioner:
 name: chef_zero
 log_level: <%= ENV['CHEF_LOG_LEVEL'] || 'auto' %>

platforms:
  - name: awslinux_v2
    driver_config:
      box: awslinux_v2
      memory: 2048
  # - name: awslinux_2018.03
  #   driver_config:
  #     box: awslinux_2018.03
  - name: centos_76
    driver_config:
      box: centos_7.6
  # - name: centos_75
  #   driver_config:
  #     box: centos_7.5
suites:
 - name: master
   run_list:
     - recipe[docker::install]
     - recipe[docker::service]
     - recipe[docker::wrappers]
     - recipe[docker::configure]
     - recipe[kube::master_install]
     - recipe[kube::master_service]
   attributes:
     phenom:
       banner: ‘Phenom Banner’
 - name: node
   run_list:
     - recipe[docker::install]
     - recipe[docker::service]
     - recipe[docker::wrappers]
     - recipe[docker::configure]
     - recipe[kube::kube_repo]
     - recipe[kube::node_install]
     - recipe[kube::node_services]
   attributes:
     phenom:
       banner: ‘Phenom Banner’
